export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED';
export const SET_INGREDIENTS_SUCCESS = 'SET_INGREDIENTS_SUCCESS';

export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';

export const ORDER_INIT = 'ORDER_INIT';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILED = 'ORDER_FAILED';
export const ORDER_LOADING = 'ORDER_LOADING';
export const ORDER_PURCHASED_RESET = 'ORDER_PURCHASED_RESET';

export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const LOGOUT = 'LOGOUT';


