export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED';
export const SET_INGREDIENTS_SUCCES = 'SET_INGREDIENTS_SUCCES';

export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';

